### ISSUE TITLE
In case of equality, sort by length of the title

### ISSUE THREAD

**Issue by Niols** [paris-branch/dancelor#197]
...or anything else that allows to put as first the most precise option. For instance, if I look for myself, I get:

![image](https://github.com/paris-branch/dancelor/assets/5920602/0759dd36-5585-4280-94b5-78282cbb9382)

Most of the time, though, I would mean myself, not myself and people. Another example:

![image](https://github.com/paris-branch/dancelor/assets/5920602/ec5d5dd5-af86-4332-9270-3bd6933b271c)

Most of the time, we'd want Aliénor, Anne-Laure or Pascaline, not them and someone else.

**Comment by R1kM** [comment]
That sounds like a good idea. If we believe that single credits should be prioritized though, what do you think about sorting by number of persons in a credit instead of length of the title ?

**Comment by Niols** [comment]
Actually, with the disappearance of credits, those examples should just not happen. We should get rid of those credits and instead allow tunes/sets/dances to have several composers/devisers.

**Comment by Niols** [comment]
See #200 and #308.
